version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_biblioteca
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    ports:
      - '${DB_PORT}:3306'

    volumes:
      - db_data:/var/lib/mysql
      - ./src/script/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
